# Generated by Django 6.0.4 on 2026-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_alter_petprofile_size_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="petprofile",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="district",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="location_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="province",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
